# name: Deploy production
#
# on:
#   release:
#     types: [published]
#
#
#
# deploy:
#   runs-on: ubuntu-latest
#   needs: ['build']
#   steps:
#
#     - name: Check Out Repo
#       uses: actions/checkout@v2
#
#     - name: Deploy to Cluster
#       id: kubectl-deploy
#       uses: dataesr/kubectl-deploy@v1
#       env:
#         KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
#       with:
#         restart: 'scanr'
#
#     - name: Notify in slack
#       run: |
#         curl -X POST -H 'Content-type: application/json' --data '{"text":"Une nouvelle version de scanR est en préprod. Vous pouvez la voir ici: http://scanr.staging.dataesr.ovh"}' ${{ secrets.SLACK_WEBHOOK }}
