name: Publish docker image and release

on:
  push:
    tags:
      - "*"

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: Log into registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -f Dockerfile -t ${{ github.repository }} .

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          docker tag ${{ github.repository }} $IMAGE_ID:latest
          docker tag ${{ github.repository }} $IMAGE_ID:${{ steps.version.outputs.version }}
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:${{ steps.version.outputs.version }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: Set date
        id: setdate
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/config/changelog-config.js
      - name: print changelog
        run: echo "${{ steps.changelog.outputs.changes }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          body: "${{ steps.changelog.outputs.changes }}"
